# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  scrapy:
    build: . # Build from the current directory (where the Dockerfile is)
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/ # Connect to the 'mongo' service
    working_dir: /app/jobs_project
  query:
    build: . # Build from the current directory (where the Dockerfile is)
    depends_on:
      - scrapy
    environment:
      MONGO_URI: mongodb://mongo:27017/ # Connect to the 'mongo' service
    working_dir: /app
    command: python query.py
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Expose the port (only for development)
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  mongo_data: # The named volume for MongoDB
